// 通用AB
let head = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"产品类型","code":"productTypeName","type" : "text","width":"120"},
    {"name":"计费产品","code":"calculatePriceName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true","entityId":"620"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true","entityId":"621"},
    
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"入库时间","code":"callInDate","type" : "text","isSum":"true"},
    {"name":"入库状态","code":"callStsName","type" : "text","isSum":"true"},
    {"name":"供应商类型","code":"supplierTenantTypeName","type" : "text"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"120"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true","entityId":"635"},
    {"name":"中转时间","code":"outGoingDate","type" : "text","width":"130"},
    {"name":"跟踪内容","code":"trackingContent","type" : "text","width":"150"},
    {"name":"跟踪时间","code":"trackingDateLast","type" : "text","width":"130"},
    {"name":"配送员姓名","code":"deliveryUserName","type" : "text"},
    {"name":"配送员电话","code":"deliveryUserPhone","type" : "text"},
    {"name":"签收时间","code":"signDate","type" : "text","width":"150"},
    //{"name":"接单时间","code":"acceptDate","type" : "text","width":"150"},
    {"name":"揽收时间","code":"collectTime","type" : "text","width":"150"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"},
    {"name":"取消人","code":"cancelOpName","width":"150","type" : "text"},
    {"name":"取消时间","code":"cancelTime","width":"150","type" : "text"},
    {"name":"取消备注","code":"cancelRemark","width":"200","type" : "text"},
    {"name":"确认取消状态","code":"cancelConfirmStsName","width":"100","type" : "text"},
    {"name":"确认取消人","code":"cancelConfirmOpName","width":"150","type" : "text"},
    {"name":"确认取消时间","code":"cancelConfirmTime","width":"150","type" : "text"},
    {"name":"确认取消备注","code":"cancelConfirmRemark","width":"200","type" : "text"}
];
// 揽件异常 待揽件  TAB
let head4 = [ 
    //{"name":"接单时间","code":"acceptDate","type" : "text","width":"150"},
    {"name":"揽收时间","code":"collectTime","type" : "text","width":"150"},
    {"name":"揽件异常","code":"isPackageExcetion","type" : "text","width":"120"},
    {"name":"异常原因","code":"exceptionTypeName","type" : "text","width":"120"},
    {"name":"异常备注","code":"exceptionRemark","type" : "text","width":"150"},
    {"name":"异常登记人","code":"exceptionOpName","type" : "text","width":"120"},
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"产品类型","code":"productTypeName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true","entityId":"620"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true","entityId":"621"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"供应商类型","code":"supplierTenantTypeName","type" : "text"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"120"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true","entityId":"635"},
    {"name":"配送员姓名","code":"deliveryUserName","type" : "text"},
    {"name":"配送员电话","code":"deliveryUserPhone","type" : "text"},
    {"name":"签收时间","code":"signDate","type" : "text","width":"150"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"},
];
// 取消TAB
let head88 = [ 
    {"name":"取消人","code":"cancelOpName","width":"150","type" : "text"},
    {"name":"取消时间","code":"cancelTime","width":"150","type" : "text"},
    {"name":"取消备注","code":"cancelRemark","width":"200","type" : "text"},
    {"name":"确认取消状态","code":"cancelConfirmStsName","width":"100","type" : "text"},
    {"name":"确认取消人","code":"cancelConfirmOpName","width":"150","type" : "text"},
    {"name":"确认取消时间","code":"cancelConfirmTime","width":"150","type" : "text"},
    {"name":"确认取消备注","code":"cancelConfirmRemark","width":"200","type" : "text"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"产品类型","code":"productTypeName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true","entityId":"620"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true","entityId":"621"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"供应商类型","code":"supplierTenantTypeName","type" : "text"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"120"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true"},
    {"name":"配送员姓名","code":"deliveryUserName","type" : "text"},
    {"name":"配送员电话","code":"deliveryUserPhone","type" : "text"},
    {"name":"签收时间","code":"signDate","type" : "text","width":"150"},
    //{"name":"接单时间","code":"acceptDate","type" : "text","width":"150"},
    {"name":"揽收时间","code":"collectTime","type" : "text","width":"150"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
  
];

// 未入库 TAB
let headNotCall = [ 
    {"name":"签收时间","code":"signDate","type" : "text","width":"150"},
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"产品类型","code":"productTypeName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"入库时间","code":"callInDate","type" : "text","isSum":"true"},
    {"name":"入库状态","code":"callStsName","type" : "text","isSum":"true"},
    {"name":"运输类型","code":"transitTypeName","type" : "text","width":"120"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"120"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true","entityId":"635"},
    {"name":"中转时间","code":"outGoingDate","type" : "text","width":"130"},
    {"name":"跟踪内容","code":"trackingContent","type" : "text","width":"200"},
    {"name":"跟踪时间","code":"trackingDateLast","type" : "text","width":"120"},
    {"name":"车牌号码","code":"plateNumber","type" : "text","width":"120"},
    {"name":"司机姓名","code":"driverName","type" : "text","width":"120"},
    {"name":"司机手机","code":"driverBill","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true","entityId":"620"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true","entityId":"621"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"配送员姓名","code":"deliveryUserName","type" : "text"},
    {"name":"配送员电话","code":"deliveryUserPhone","type" : "text"},
    //{"name":"接单时间","code":"acceptDate","type" : "text","width":"150"},
    {"name":"揽收时间","code":"collectTime","type" : "text","width":"150"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"},
];

// 导入 表格
let headImport = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"计费产品","code":"calculatePriceName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"导入时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true","entityId":"622"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true","entityId":"623"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"仓管员","code":"warehourseKeeperName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
];
// 导入 表格
let headFeeImport = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"计费产品","code":"calculatePriceName","type" : "text","width":"120"},
    {"name":"导入时间","code":"importFeeTime","type" : "text","width":"120"},
    {"name":"导入人","code":"importFeeOpName","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"仓管员","code":"warehourseKeeperName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
];

// 计费产品类型表格
let headCalculate = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"计费产品","code":"calculatePriceName","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"仓管员","code":"warehourseKeeperName","type" : "text"},
    {"name":"供应商类型","code":"supplierTenantTypeName","type" : "text"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"120"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true"},
    {"name":"中转时间","code":"outGoingDate","type" : "text","width":"130"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
];
// 系统导入-审核TAB
let headAudit = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"审核状态","code":"auditStsName","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true","entityId":"618"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true","entityId":"619"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
];
// 推送费用
let headPush = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"产品类型","code":"productTypeName","type" : "text","width":"120"},
    {"name":"计费产品","code":"calculatePriceName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"推送状态","code":"pushStatusName","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"手工单号","code":"manualNum","type" : "text","width":"120"},
    {"name":"期待到货时间","code":"waitArriveDate","type" : "text","width":"150"},
    {"name":"期待上门时间","code":"prePickupDate","type" : "text","width":"200"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    // {"name":"客户联系人","code":"customerTenantPrincipal","type" : "text","width":"120"},
    // {"name":"客户联系手机","code":"customerTenantPhone","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"运单来源","code":"sourceTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"审核时间","code":"auditDate","type" : "text","width":"150"},
    {"name":"三方结算","code":"payConsignorFlagName","type" : "text","width":"120"},
    {"name":"三方结算状态","code":"payConsignorStateName","type" : "text","width":"120"},
    {"name":"结算店铺","code":"payConsignorName","type" : "text","width":"120"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省","code":"sourceProvinceName","type" : "text","width":"100"},
    {"name":"发货市","code":"sourceCityName","type" : "text","width":"100"},
    {"name":"发货区","code":"sourceCountyName","type" : "text","width":"100"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省","code":"destProvinceName","type" : "text","width":"100"},
    {"name":"收货市","code":"destCityName","type" : "text","width":"100"},
    {"name":"收货区","code":"destCountyName","type" : "text","width":"100"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    {"name":"需求运输类型","code":"transportTypeName","type" : "text"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"结算收入合计","code":"orderIncomeDouble","type" : "text","isSum":"true"},
    {"name":"到付上浮费","code":"floatingPriceDouble","type" : "text","isSum":"true"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"包装数据","code":"packingInfo","type" : "text","width":"150"},
    {"name":"计费件数","code":"billingNumber","type" : "text","isSum":"true"},
    {"name":"计费体积（方）","code":"billingVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"计费重量（公斤）","code":"billingWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"调出数量","code":"callOutCount","type" : "text","isSum":"true"},
    {"name":"入库数量","code":"callInCount","type" : "text","isSum":"true"},
 
    {"name":"供应商类型","code":"supplierTenantTypeName","type" : "text"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"120"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true"},
    {"name":"中转时间","code":"outGoingDate","type" : "text","width":"130"},
    {"name":"跟踪内容","code":"trackingContent","type" : "text","width":"150"},
    {"name":"跟踪时间","code":"trackingDateLast","type" : "text","width":"130"},
    {"name":"配送员姓名","code":"deliveryUserName","type" : "text"},
    {"name":"配送员电话","code":"deliveryUserPhone","type" : "text"},
    {"name":"签收时间","code":"signDate","type" : "text","width":"150"},
    //{"name":"接单时间","code":"acceptDate","type" : "text","width":"150"},
    {"name":"揽收时间","code":"collectTime","type" : "text","width":"150"},
    {"name":"客服专员","code":"customBusinessName","type" : "text"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text"},
    {"name":"采购员","code":"purchaseUserName","type" : "text"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"},
];
 
// 切换 TAB 
let  tabs = [
    {code:"ordersNum",name:"全部运单",orderState:"-1",num:"*",item:"toOrdersNumTem",itemType:"function", active:true,"router":"orders","showOrderTab":true},
    {code:"waitDealOrderNum",name:"待分配",orderState:"2",num:"*",item:"toWaitDealOrderNum",itemType:"function","router":"orders","showOrderTab":true},
    // {code:"waitReceiveOrderNum",name:"待接单",orderState:"3",num:"*",item:"toWaitReceiveOrderNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"waitPackageOrderNum",name:"待取件",head:head4,ordersTable:"ordersPackageTable",orderState:"3,4",num:"*",item:"toWaitPackageOrderNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"transferOrderNum",name:"运输中",orderState:"5",num:"*",item:"toTransferOrderNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"signOrderNum",name:"已签收",orderState:"6",num:"*",item:"toSignOrderNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"notCallinOrderNum",name:"未入库",num:"*",orderState:"-2",head:headNotCall,ordersTable:"ordersNotCallTable",item:"toNotCallInNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"waitPayOrderNum",name:"待付款",num:"*",orderState:"-3",item:"toNotPayNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"cancalOrderNum",name:"已取消",orderState:"88",num:"*",head:head88,ordersTable:"ordersCancelTable",item:"toCancalOrderNum",itemType:"function","router":"orders","showOrderTab":true},
    {code:"exceptionOrderNum",name:"异常件",num:"*",item:"toExceptionView","router":"cmAbnormal",itemType:"function","showOrderTab":false}, 
];
let tabsCalculate = [
    {code:"waitOrder",name:"待匹配",selectType:"1",num:"*"},
    {code:"doingOrder",name:"已匹配",selectType:"2",num:"*"}
];
export{
    head,
    tabs,
    headImport,
    headAudit,
    headFeeImport,
    tabsCalculate,
    headCalculate,
    headPush
}
