// 通用AB
let head = [ 
    {"name":"发货区域","code":"sourceRegionName","type" : "text","width":"120"},
    {"name":"目的区域","code":"destRegionName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"子单号","code":"transitTrackingNum","type" : "text","width":"150"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"150"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"中转类型","code":"transitTypeName","type" : "text","width":"120"},
    {"name":"供应商类型","code":"supplierTenantTypeName","type" : "text"},
    {"name":"供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","isSum":"true"},
    {"name":"中转结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"中转时间","code":"outGoingDate","type" : "text","width":"150"},
    {"name":"中转创建时间","code":"transferCreateDate","type" : "text","width":"150"},
    {"name":"对接状态","code":"transitStateName","type" : "text","width":"100"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货店仓","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"中转件数","code":"transferPackageNumber","type" : "text","isSum":"true"},
    {"name":"中转体积（方）","code":"transferPackageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"中转重量（公斤）","code":"transferPackageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"配送员姓名","code":"deliveryUserName","type" : "text"},
    {"name":"配送员电话","code":"deliveryUserPhone","type" : "text"},
    {"name":"中转备注","code":"remarks","width":"200","type" : "text"}
   
];
let headAdd = [ 
    {"name":"发货区域","code":"regionName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"子单号","code":"transitTrackingNum","type" : "text","width":"150"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"上次供应商类型","code":"supplierTenantTypeName","type" : "text","width":"150"},
    {"name":"上次供应商名称","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"上次中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货店仓","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"上次中转件数","code":"transferPackageNumber","type" : "text","isSum":"true","width":"150"},
    {"name":"上次中转体积（方）","code":"transferPackageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"上次中转重量（公斤）","code":"transferPackageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
];

let headAddList = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"品牌","code":"brandName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货店仓","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"客户备注","code":"customerRemarks","width":"200","type" : "text"},
    {"name":"内部备注","code":"remarks","width":"200","type" : "text"}
];

let tabs = [
    {name: "专线物流", active: true,selectType: 1},
    {name: "快递快运", selectType: 2 }
];
export{
    head,
    headAdd,
    tabs,
    headAddList
}
