// 通用AB
let head = [ 
    {"name":"发货区域","code":"regionName","type" : "text","width":"120"},
     // {"name":"中转创建时间","code":"transferCreateDate","type" : "text","width":"150"},
    {"name":"中转时间","code":"outGoingDate","type" : "text","width":"150"},
    {"name":"批次号","code":"batchNumAlias","type" : "text","width":"150"},
    {"name":"供应商","code":"supplierTenantName","type" : "text","width":"150"},
    {"name":"中转单号","code":"outgoingTrackingNum","type" : "text","width":"150"},
    {"name":"多次中转","code":"transitFlagName","type" : "text","width":"120"},
    {"name":"中转单数","code":"orderNum","type" : "text","width":"150","isSum":"true"},
    {"name":"运费收入合计","code":"orderIncomeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"中转费用","code":"outgoingFeeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"中转毛利","code":"profitFeeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"中转毛利率","code":"profitFeeRate","type" : "text","width":"120"}
];

// 单票
let headOrder = [ 
    {"name":"所属区域","code":"regionName","type" : "text","width":"120"},
    {"name":"运单号","code":"trackingNum","type" : "text","width":"120"},
    {"name":"客户单号","code":"ordNum","type" : "text","width":"150"},
    {"name":"采购单号","code":"purchaseNum","type" : "text","width":"120"},
    {"name":"多次中转","code":"transitFlagName","type" : "text","width":"150"},
    {"name":"客户类型","code":"customerTypeName","type" : "text","width":"120"},
    {"name":"下单客户","code":"customerTenantName","type" : "text","width":"200"},
    {"name":"运单状态","code":"orderOutStateName","type" : "text","width":"120"},
    {"name":"运单类型","code":"orderTypeName","type" : "text","width":"120"},
    {"name":"下单时间","code":"createDate","type" : "text","width":"150"},
    {"name":"实际托运时间","code":"billingDate","type" : "text","width":"150"},
    {"name":"发货店仓","code":"consignorName","type" : "text","width":"120"},
    {"name":"发货人","code":"consignorLinkmanName","type" : "text","width":"120"},
    {"name":"发货手机","code":"consignorBill","type" : "text","width":"120"},
    {"name":"发货电话","code":"consignorTelephone","type" : "text","width":"120"},
    {"name":"发货省市区","code":"sourceCityAddr","type" : "text","width":"120"},
    {"name":"发货详细地址","code":"sourceAddress","type" : "text","width":"200"},
    {"name":"收货客户","code":"consigneeName","type" : "text","width":"120"},
    {"name":"收货人","code":"consigneeLinkmanName","type" : "text","width":"120"},
    {"name":"收货手机","code":"consigneeBill","type" : "text","width":"120"},
    {"name":"收货电话","code":"consigneeTelephone","type" : "text","width":"120"},
    {"name":"收货省市区","code":"destCityAddr","type" : "text","width":"120"},
    {"name":"收货详细地址","code":"destAddress","type" : "text","width":"200"},
    {"name":"前端交货方式","code":"beginDeliveryTypeName","type" : "text"},
    {"name":"末端交货方式","code":"endDeliveryTypeName","type" : "text"},
    // {"name":"结算方式","code":"paymentTypeName","type" : "text"},
    // {"name":"支付方式","code":"payWayName","type" : "text"},
    {"name":"货品名","code":"goodsName","type" : "text","width":"120"},
    {"name":"打包件数","code":"packageNumber","type" : "text","isSum":"true"},
    {"name":"打包体积（方）","code":"packageVolume","type" : "text","isSum":"true","width":"150"},
    {"name":"打包重量（公斤）","code":"packageWeight","type" : "text","isSum":"true","width":"150"},
    {"name":"收入","code":"orderIncomeDouble","type" : "text","isSum":"true","width":"120"},
    {"name":"异常增款","code":"exceptionInscreaseFeeDouble","type" : "text","isSum":"true","width":"120"},
    {"name":"派车时间","code":"dispatchTime","type" : "text","width":"150"},
    {"name":"派车分摊费用","code":"dispatchFeeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"干线发车时间","code":"departTime","type" : "text","width":"150"},
    {"name":"干线分摊费用","code":"departFeeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"异常赔款","code":"exceptionDecreaseFeeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"一次中转时间","code":"outgoingDateOne","type" : "text","width":"150"},
    {"name":"一次中转供应商","code":"supplierTenantIdOneName","type" : "text","width":"200"},
    {"name":"一次中转单号","code":"outgoingTrackingNumOne","type" : "text","width":"120"},
    {"name":"一次中转费用","code":"outgoingFeeOneDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"一次中转件数","code":"packageNumberOne","type" : "text","isSum":"true"},
    {"name":"一次中转体积（方）","code":"packageVolumeOne","type" : "text","isSum":"true","width":"150"},
    {"name":"一次中转重量（公斤）","code":"packageWeightOne","type" : "text","isSum":"true","width":"150"},
    {"name":"二次中转时间","code":"outgoingDateTwo","type" : "text","width":"150"},
    {"name":"二次中转供应商","code":"supplierTenantIdTwoName","type" : "text","width":"200"},
    {"name":"二次中转单号","code":"outgoingTrackingNumTwo","type" : "text","width":"120"},
    {"name":"二次中转费用","code":"outgoingFeeTwoDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"二次中转件数","code":"packageNumberTwo","type" : "text","isSum":"true"},
    {"name":"二次中转体积（方）","code":"packageVolumeTwo","type" : "text","isSum":"true","width":"150"},
    {"name":"二次中转重量（公斤）","code":"packageWeightTwo","type" : "text","isSum":"true","width":"150"},
    {"name":"三次中转时间","code":"outgoingDateThree","type" : "text","width":"150"},
    {"name":"三次中转供应商","code":"supplierTenantIdThreeName","type" : "text","width":"200"},
    {"name":"三次中转单号","code":"outgoingTrackingNumThree","type" : "text","width":"120"},
    {"name":"三次中转费用","code":"outgoingFeeThreeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"三次中转件数","code":"packageNumberThree","type" : "text","isSum":"true"},
    {"name":"三次中转体积（方）","code":"packageVolumeThree","type" : "text","isSum":"true","width":"150"},
    {"name":"三次中转重量（公斤）","code":"packageWeightThree","type" : "text","isSum":"true","width":"150"},
    {"name":"超三次中转费用","code":"outgoingFeeManyDouble","type" : "text","width":"150","isSum":"true"},
    {"name":"超次中转件数","code":"packageNumberMany","type" : "text","isSum":"true"},
    {"name":"超次中转体积（方）","code":"packageVolumeMany","type" : "text","isSum":"true","width":"150"},
    {"name":"超次中转重量（公斤）","code":"packageWeightMany","type" : "text","isSum":"true","width":"150"},
    {"name":"单票毛利","code":"profitFeeDouble","type" : "text","width":"120","isSum":"true"},
    {"name":"单票毛利率","code":"profitFeeRate","type" : "text","width":"120"},
    {"name":"销售专员","code":"salesmanBusinessName","type" : "text","width":"120"},
    {"name":"销售部门","code":"salesmanOrgName","type" : "text","width":"120"},
    {"name":"毛利更新时间","code":"opDate","type" : "text","width":"150"},
];
export{
    head,
    headOrder
}
